spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/food_reviews
spring.datasource.username=postgres
spring.datasource.password=Ihatethis2!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true